services:
  backend:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
    container_name: reservation-backend
    restart: always
    volumes:
      - ./files:/app/files
      - ./qrcodes:/app/qrcodes
      - ./pdf:/app/pdf

  db:
    image: postgres:14.21-trixie
    ports:
      - 5432:5432
    volumes:
      - db-data:/app/db-data
    container_name: reservation-db
    environment:
      POSTGRES_DB: reservation
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres

volumes:
  db-data: