spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/reservation
    username:
    password:
    driverClassName: org.postgresql.Driver

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public

security:
  jwt:
    expiration-time: 3600000
    secret: 5367566859703373367639792F423F452848284D6251655468576D5A71347437

notification-api:
  client-id: mf0nh0grffote37wbf7bcw3axh
  client-secret: pe293si9q3095cmqho7po54lwdiq2yj6e9ou4pw7p2vi3ebexa2yvgaf4w

